name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build-test
        run: |
          npm ci
          npm run build-test
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: $({secrets.LIGHTHOUSE_APP_TOKEN})